<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerMXitJsR\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerMXitJsR/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerMXitJsR.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerMXitJsR\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerMXitJsR\App_KernelDevDebugContainer([
    'container.build_hash' => 'MXitJsR',
    'container.build_id' => '8a098b92',
    'container.build_time' => 1605018251,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerMXitJsR');
